export const styles = {
  sheet: {
    width: "90%",
    mx: "auto",
    backgroundColor: "lightblue",
    mt: 4,
    p: 2,
    borderRadius: "4px",
    boxShadow: "md",
    display: "flex",
    flexDirection: "column",
    whiteSpace: "pre-line",
  },
  container: {
    backgroundColor: "white",
    mx: "auto",
    width: "100%",
    height: "100%",
    p: 3,

    borderRadius: "10px",
  },
  card: {
    backgroundColor: "lightblue",
    width: "98%",
    mx: "auto",
    height: "100%",
    p: 3,
    borderRadius: "10px",
    whiteSpace: "pre-line",
  },
  mobileCard: {
    backgroundColor: "lightblue",
    width: "100%",
    mx: "auto",
    height: "100%",
    p: 1.5,
    borderRadius: "10px",
    whiteSpace: "pre-line",
  },
  tableCard: {
    backgroundColor: "lightblue",
    width: "98%",
    mx: "auto",
    maxHeight: "30%",
    overflow: "auto",
    p: 3,
    borderRadius: "10px",
    whiteSpace: "pre-line",
  },
};
