export const styles = {
  sheet: {
    width: "90%",
    mx: "auto",
    backgroundColor: "lightblue",
    mt: 4,
    p: 2,
    borderRadius: "4px",
    boxShadow: "md",
    display: "flex",
    flexDirection: "column",
  },
  container: {
    backgroundColor: "white",
    mx: "auto",
    width: "100%",
    height: "100%",
    p: 3,
    my: 2,
    borderRadius: "10px",
  },
  card: {
    backgroundColor: "lightblue",
    outline: "1px solid grey",
    width: "100%",
    height: "100%",
    p: 3,
    borderRadius: "10px",
  },
};
